#!/bin/bash

# Railway Deployment Guide - Quick Start
# ======================================

echo "🚀 RAILWAY DEPLOYMENT GUIDE"
echo "=============================="
echo ""
echo "Follow these steps to deploy your app:"
echo ""
echo "STEP 1: Go to Railway"
echo "----------------------"
echo "Open your browser and visit: https://railway.app"
echo ""
echo "STEP 2: Sign In with GitHub"
echo "----------------------------"
echo "Click 'Login with GitHub' button"
echo "Authorize Railway to access your repositories"
echo ""
echo "STEP 3: Create New Project"
echo "--------------------------"
echo "1. Click 'New Project' button"
echo "2. Select 'Deploy from GitHub repo'"
echo "3. Choose: 'abhiishekbisht/Marksheet-Generator'"
echo "4. Click 'Deploy Now'"
echo ""
echo "STEP 4: Add MySQL Database"
echo "--------------------------"
echo "1. In your project dashboard, click '+ New'"
echo "2. Select 'Database'"
echo "3. Choose 'Add MySQL'"
echo "4. Railway will create and connect MySQL automatically"
echo ""
echo "STEP 5: Configure Environment Variables"
echo "----------------------------------------"
echo "1. Click on your Flask service (web app)"
echo "2. Go to 'Variables' tab"
echo "3. Add these variables:"
echo ""
echo "   SECRET_KEY=your-super-secret-key-change-this-random"
echo "   FLASK_ENV=production"
echo "   FLASK_DEBUG=False"
echo "   COLLEGE_NAME=GULZAR GROUP OF INSTITUTIONS"
echo "   COLLEGE_ADDRESS=Academic Excellence Since 1995"
echo ""
echo "   NOTE: Database variables are auto-configured by Railway!"
echo ""
echo "STEP 6: Initialize Database"
echo "----------------------------"
echo "1. Click on your Flask service"
echo "2. Go to 'Settings' tab"
echo "3. Scroll to 'Deploy Logs'"
echo "4. Wait for deployment to complete"
echo "5. Click 'Connect' → Select 'Connect via CLI'"
echo "6. Run: railway run python init_db.py"
echo ""
echo "STEP 7: Get Your URL"
echo "--------------------"
echo "1. Click on your Flask service"
echo "2. Go to 'Settings' tab"
echo "3. Click 'Generate Domain' (under Networking)"
echo "4. Your app will be live at: https://your-app.up.railway.app"
echo ""
echo "✅ DEPLOYMENT COMPLETE!"
echo "========================"
echo "Your marksheet app is now live with MySQL database!"
echo ""
echo "Next: Visit your Railway URL and login with:"
echo "  Admin: admin / admin123"
echo "  Teacher: teacher / teacher123"
echo ""

# Open Railway in browser
echo "Opening Railway in your browser..."
sleep 2
open https://railway.app
